### ISSUE TITLE
Motivation du cours

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#1]
Je pense que le cours serait bien introduit si il commençait par un problème concret, pas de la théorie, pas simplifié à outrance pour être « pédagogique » : réel mais pas compliqué, intéressant et motivant.

Comme cela, on pourrait motiver plus facilement les étudiants en mode projet.

Par des trucs autour de  http://microbit.org/fr/code/ (mais je vois javascript ou python et pas de java !) 
Avec java, je vois https://github.com/tiagorodrigues11/Java-Thymio

Il y a en java  https://people.irisa.fr/Martin.Quinson/Teaching/PLM/ un projet de Martin Quinson que je vous ai décrit il y a quelques années et avec lequel je suis en contact.

Je proposerai des exemples de sujets.

**Comment by pbettens** [comment]
tiens plm pourrait être intéressant. on pourrait ajouter ça à code studio si quelqu'un y regarde de plus près.
