### ISSUE TITLE
envl / tous les td : nom de la haute école

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#100]
le nom de la haute école HE2B est « Haute École Bruxelles-Brabant » sans « de » entre « École » et « Bruxelles ».

**Comment by YoungFrog** [comment]
Ceci a été arrangé upstream (https://git.esi-bru.be/mcodutti/template-latex-esi) il reste à mettre à jour le(s) répertoire(s) style-esi de notre dépôt.

**Comment by nvansteenkiste** [comment]
réglé par @mcodutti
