### ISSUE TITLE
envl / tous les td : nom de logiciel et style

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#103]
dans le Tutoriel 1 du td02, on a putty puis \textit{putty}. je pense que comme pour les commandes linux, il faut unifier. dans tous les td, pour tous les noms de logiciels.

**Comment by mcodutti** [comment]
Je viens d'ajouter dans le style ESI (en m'inspirant des noms dans html5)

- `\kbd` : pour un entrée clavier, une commande à taper telle quelle
- `\samp` : pour le résultat d'une commande, un output de programme
- `\abbr` : pour une abréviation, un sigle, acronyme
- `\name` : pour un nom de logiciel

Pour le moment, `\kbd` et `\samp` sont des `\texttt` et `\abbr` et `\name` des `\bsc`.
Le tout est dans common.sty et automatiquement chargé dans tous les types de documents ESI (cf. doc mise à jour)
