### ISSUE TITLE
envl / guide visuel : table des matières

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#108]
le chapitre 11 Chemin relatif est indiqué commencer à la page 7. Malheureusement, il se trouve en page 6.

**Comment by YoungFrog** [comment]
J'ai màj la toc mais rien d'autre. Il faudrait peut être réviser ce document avec de le publier (ou simplement ne pas le publier -- il me semble avoir peu d'intérêt).
