### ISSUE TITLE
envl / td02 : quick reference

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#118]
il est fait mention d'un « quick reference » juste avant l'exercice 7. je ne le trouve pas sur poESI.

**Comment by YoungFrog** [comment]
Je n'ai pas non plus vu de quick reference sur poesi.  @pbischop sais-tu ce qu'il en est ? S'il y en avait une l'an passé, peut-on juste reprendre le même document ?

**Comment by nvansteenkiste** [comment]
obsolète dans la version actuelle des td
