### ISSUE TITLE
Syllabus : Chapitre 3 Les algorithmes et les programmes

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/dev1#12]
Je poste les remarques au fur et à mesure de la lecture, peut-être que la suite répondra à mes questions...

Dans l'ordinogramme, je trouve dommage de ne pas voir apparaitre l'information "en connaissant le rayon"

Introduction du pseudo code pour la circonférence d'un cercle : 
- je ne comprends pas l'utilité de "type var" dans l'algorithme qui ne doit faire qu'un return
- je regrette l'absence d'un "fin algo" ou symbole équivalent. Mon ressenti à ce stade est que c'est l'indentation qui symbolise le contenu du bloc.

**Comment by pbettens** [comment]
oui, c'est l'indentation qui symbolise un bloc… un peu comme en python.
