### ISSUE TITLE
envl /td02 - exercice 3 - notions non vues

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#123]
L'exercice 3 fait référence aux notions de compilation, byte code, machine virtuelle qui n'ont pas encore été vues au cours (en tout cas, perso en 4h j'ai pas juste eu le temps de l'évoquer en 1 ou 2 phrases)
Intuitivement, ils auront envie de répondre 'x' comme permission pour le .java

**Comment by nvansteenkiste** [comment]
je me demandais aussi ceci : le .class, les autres doivent-il avoir le droit d'écriture sur lui ou sur le dossier le contenant. je pense au compilateur qui doit produire le .class.

**Comment by mcodutti** [comment]
Pour moi, pour pouvoir créer ou détruire un fichier, il faut (et il suffit) d'avoir le droit en écriture sur le dossier le contenant.

**Comment by mcodutti** [comment]
Cette notion vient maintenant dans le TD7 et ils auront eu le temps d'appréhender le concept de compilation.
