### ISSUE TITLE
envl / td03 : contenu sur poESI

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#129]
probablement pas l'objet d'une issue, n'hésitez pas à me dire quel canal utiliser si celui-ci n'est pas le bon.

on fait référence à de multiples fichiers annexes pour la réalisation des exercices et pas à pas du td03. je trouve dommage que ces fichiers ne soient pas disponibles sur poESI. impossible de faire le td sans passer par l'esi, donc pas beaucoup d'envie de lire le td hors les murs de l'école.

**Comment by nvansteenkiste** [comment]
cette issue reste d'actualité me semble-t-il. comme je quitte l'ue, je m'en désassigne :-)

**Comment by YoungFrog** [comment]
On a des soucis similaires avec le td1 (qui fait référence au répertoire ~/dev1 et au fichier welcome sur linux1), et sûrement d'autres (j'imagine si on fait référence aux permissions et aux groupes, spécifiques à linux1). Chaque souci aurait une solution différente, donc mon avis est qu'on peut juste vivre avec ce fait, et je propose de fermer l'issue. Paf. Rouvrez si le coeur vous en dit !
