### ISSUE TITLE
Syllabus : Chapitre 4 Spécifier le problème

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/dev1#13]
- Les noms : Définition de variable : je ne comprends pas le "est" dans "par une autre — est variable — "

- Les types : dans toute la suite du chapitre, on retrouve : on y retrouve "réel" ou "entier", ...  et pas "real" ou "integer" ou ... comme annoncé dans l'encadré des différents types

**Comment by pbettens** [comment]
- je voulais dire "parce qu'elle est variable…puisque c'est une variable". je tente de reformuler.
