### ISSUE TITLE
intersection "orienté objet" et "fonctionnel"

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#138]
https://github.com/HEB-ESI/dev1/blob/c09fa5b91d7a5de432f25fc7390a9b4b9cef7a23/cours-developpement/syllabus/base/premprogrammes.tex#L53-L66

Scala est indiqué dans les deux classes de langages (OO et fonctionnels), qui sont pourtant présentées comme a priori différentes. Il me semble qu'on en dit trop, ou trop peu... (Wikipedia souligne qu'ils sont rares, les langages à relever des deux catégories...)

Cela étant, je trouve que c'est un peu tôt pour présenter ces différentes catégories de langages. Je doute que l'étudiant retire quoique ce soit d'une telle classification à ce moment. Quel est votre avis ?

**Comment by mcodutti** [comment]
Pour ma part, je n'y ai consacré que +/- 10' cette année (j'y reviendrai peut-être plus tard).
Je garderais quand même cette partie. Ils ne peuvent pas tout comprendre mais j'aime bien faire passer l'idée que : 
- Il existe une histoire des langages
- Qu'est-ce qui motive à inventer un nouveau langage, une nouvelle classe de langages ?
- Qu'est-ce qui pousse à les faire se ressembler à d'autres ?
- Pourquoi ne pas en garder un seul ?

Plus tard, je prend appui sur ces notions pour justifier certains choix de Java qui restent criticables mais qui sont au moins cohérents.
