### ISSUE TITLE
javl / td4 - exercice 11 - bug

### ISSUE THREAD

**Issue by SebDrobisz** [HEB-ESI/dev1#139]
Erreur avec la suite
1 ; 2 ; 3 ; 2

Solution : La valeur antécédente devrait être modifiée à chaque passage dans la boucle.

Il y aura toujours une erreur avec la suite suivante :
1 ; 2 ; 3 ; 2 ; 4
Puisque dans la condition, on ne mémorise pas le status de la suite dans la variable `croissante`.

Solution...

**Comment by SebDrobisz** [comment]
En effet, je n'avais fait que corriger une erreur relevée par un étudiant. Maintenant la tienne. Je n'ai pas essayé ni réfléchi à d'autres cas particuliers.

**Comment by YoungFrog** [comment]
si croissante est false au début, ça ne va pas changer ensuite.

par ailleurs dans le premier passage de boucle, antécédent = valeur par construction, donc croissante sera forcément false.

J'ai tenté de résoudre tout cela dans 8d5deb4ce40ea33e305aa10aa179594067e9d291

**Comment by SebDrobisz** [comment]
Indeed. La prochaine fois, je prendrai le temps de faire la correction correctement.
Merci pour ces fixS
