### ISSUE TITLE
envl / td4 : 1.4 Passer à la couleur + Exercice 4

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#153]
après le 3e item qui est un exemple d'utilisation dans la classe Color, il serait bien d'ajouter un 4e item d'exemple d'utilisation _hors_ de la classe Color :  

    System.out.println(Color.toRed("Hello ") + Color.toGreen("World !"));

je dis ça car les étudiants que j'ai en labo créent spontanément une nouvelle classe pour répondre à l'exercice 4. ce qui est une bonne idée plutôt que de chipoter dans la classe Color.

**Comment by fservais-heb** [comment]
Ils n'ont pas encore vu les méthodes et appels de méthodes en labo-java à ce moment-là.
Mais ce n'est pas nécessairement un soucis (au contraire) :-)

**Comment by nvansteenkiste** [comment]
obsolète dans la nouvelle version des td
