### ISSUE TITLE
Déclaration tableau et méthode non statique

### ISSUE THREAD

**Issue by SebDrobisz** [HEB-ESI/dev1#155]
Section 9.4.4.
Il y a un exemple de code java qui donne un exemple de retour d'un tableau. Il y a deux erreurs selon moi.
1° La déclaration du tableau est mauvaise 
```java
is[] = new int[10]
```
Je corrigerai en :
```java
int[] is = new int[10]
```
2° Est-ce normal que la méthode ne soit pas statique ?

Si c'est bon pour vous je ferai les changements.

**Comment by YoungFrog** [comment]
j'ai commité le chgt. C'est pas que je voulais t'empêcher de le faire mais puisque j'étais dans le code pour lire le contexte, ça me semblait aussi facile de faire le changement directement ;)
