### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#156]
Il faudra envisager de mentionner les exceptions dans le syllabus.

Une source d'inspiration : https://github.com/HEB-ESI/DEV1-JAV-Slides/blob/master/sources/chapitre-erreur.tex

**Comment by pbettens** [comment]
jusqu'ou aller pour simplement introduire sans marcher sur la matière de dev2 ?

**Comment by YoungFrog** [comment]
Sans trop savoir ce qui se fait dans DEV2, je propose de simplement reprendre les anciens slides  (https://github.com/HEB-ESI/DEV1-JAV-Slides/blob/master/sources/chapitre-erreur.tex) sous forme d'une nouvelle section juste avant la "9 JUnit"

Il faudra aussi revoir le td08 qui "introduit les exceptions" mais le mot "throw" n'apparait pas dans le texte du td.

tu peux m'assigner, je veux bien le faire.

**Comment by pbettens** [comment]
merci. je ne sais pas si tu te proposes pour le cours ou pour le td ou pour les deux. 

si tu veux bien, tu peux rédiger le chapitre. on en fera un errata à diffuser et on l’intègrera l'an prochain dans le syllabus. (c'est comme nous avions fait pour les tests).

je ne sais pas s'il faut mettre ça dans la partie II ou dans la partie IV (compléments)… mais ça on peut décider plus tard.

**Comment by YoungFrog** [comment]
@pbettens  Je propose https://github.com/HEB-ESI/dev1/blob/master/cours-developpement/syllabus/pdf/errata1-exceptions.pdf (le source est dans base/exceptions.tex mais je n'ai pas ajouté de \input)

Je n'ai finalement pas modifié le TD : throw apparait dans le code, et c'est probablement suffisant. Je supprime le tag labo java.

**Comment by pbettens** [comment]
merci. c'est déjà bien. je me dis que c'est peu-être un peu court mais je ne vois pas « comme » ça qu'ajouter. si je trouve j'ajoute ;-) 

j'ajouterai l'input dans le master plus tard (c'est de toute façon pour l'an prochain). début de semaine prochaine, j'ajoute l'errata à poési. 

ça convient à tous ?

**Comment by pbettens** [comment]
publié

**Comment by YoungFrog** [comment]
Merci. Et merci aussi pour tes ajoutes pertinentes.
