### ISSUE TITLE
envl / td5 git script et java

### ISSUE THREAD

**Issue by lechjo01** [HEB-ESI/dev1#157]
Lors de l'exécution du script test.sh sur linux1, un étudiant à reçu le message suivant :

Error occurred during initialization of VM Could not allocate metaspace

On a déjà eu un soucis avec l'alias des commandes java et javac sur linux1.

La solution était d'utiliser les commandes ci-dessous : 

javac -J-XX:-UseCompressedClassPointers

javadoc -J-XX:-UseCompressedClassPointers

jar -J-XX:-UseCompressedClassPointers 

java -XX:-UseCompressedClassPointers

J'essaie de faire un test demain pour vérifier cette solution.

**Comment by lechjo01** [comment]
Après avoir réalisé un test sur `linux1`, il faut mettre à jour le script comme suit : 

```
#!/bin/sh
compileProject () {
        mkdir -p build/
        javac -J-XX:-UseCompressedClassPointers -d build/ src/helloworld/HelloWorld.java
}
runProject () {
        java -XX:-UseCompressedClassPointers -cp build/ helloworld.HelloWorld
}
expected_output='Hello, World !'
compileProject
output=$(runProject)
if [ "$output" = "$expected_output" ]; then
        echo Test réussi.
else
        echo Test échoué.
        echo Sortie attendue: $expected_output
        echo Sortie obtenue: $output
fi
```

**Comment by pbettens** [comment]
qui a la main sur ce script et peut le faire ? 
(je ne peux pas y regarder avant vendredi)

**Comment by YoungFrog** [comment]
Bon j'ai fixé ceci pour faire plaisir à @pbettens qui semble fort pressé ;)

Merci @jechjo01 pour la solution à ce problème étrange
