### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#158]
Dans le syllabus de développement, il est écrit

>  Dans ce cas, c’est un commentaire destiné à la documentation javadoc.
Nous y reviendrons.

Mais on y revient jamais !
L'année passée, on avait des slides là-dessus dans le cours de Java de dev1

**Comment by pbettens** [comment]
damned ! j'ajouterai ça :-)

**Comment by YoungFrog** [comment]
Duplicate of #4
