### ISSUE TITLE
Tests unitaires

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#161]
Je serais partisan que
- le plan de test intègre une colonne en plus qui décrit le test (pq on le fait / ce qu'on veut tester)
- la méthode correspondante ne soit pas numérotée mais décrive le test (ex: max2TousEgaux)
Si ça vous va, je veux bien faire le changement.

**Comment by YoungFrog** [comment]
ça me va, merci. Remarque mineure la colonne nom risque d'être partiellement redondante avec la colonne description, je n'insisterais donc pas sur cette dernière

**Comment by npettiaux** [comment]
Je pense comme Marco qu'une description textuelle du test est si possible bienvenue car elle est plus claire qu'une simple numérotation. Effectivement, cela peut être redondant avec la description. 
Je lis dans http://javafortesters.com/ (sample book, page 37) un commentaire à mon avis intéressant : 
Naming JUnit Test Methods
A lot of people don’t give enough thought to JUnit test method names. And use
names like addTest or addNumbers . I try to write names that:
• explain the purpose of the method without writing additional comments
• describe the capability or function we want to check
• show the scope of what is being checked

**Comment by npettiaux** [comment]
Dans le texte de Pierre, que j'apprécie, j'ajouterais 
* le nom de la classe de test doit terminer par Test (c'est une habitude, au même titre que le fait que le nom d'une classe en java commence toujours par une majuscule)
* une definition récapitulative du *plan de test* (par exemple en page 3, avant le paragraphe commençant par Remarque) 
Un **plan de test** est donc une liste ou un tableau reprenant un certain nombre d'exemples qui mettent en œuvre la méthode testée sur des cas tels que ceux décrits ci-dessus et permettent de faire apparaître des problèmes lors de l'exécution automatique. Chacun des tests sera défini par une méthode qui porte un nom qui explique l'objectif du test sans la nécessité de commentaires additionnels. Autant que possible, ce nom décrit aussi la portée ou le contexte de ce qui est vérifié.
