### ISSUE TITLE
ctrl+d

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#163]
https://github.com/HEB-ESI/dev1/blob/c87bd2ee6354b38645d55794f079409fa9ab1024/labo-cli/labo-cli-07-linux/labo-cli-07.tex#L186

Je pense qu'il faudrait préciser "caractères équivalents" [cf `Character.isWhitespace`](https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isWhitespace(char)) Ils ne trouveront pas tout seul à mon avis.

La remarque "pas de Ctrl-d ici" est un peu hors de propos car ce n'est pas Ctrl+D en tant que caractère (càd ASCII 4) qui indique EOF : un fichier peut contenir de tels caractères, cela n'empêchera pas grep, cat et leurs amis de lire le fichier jusqu'à son terme. Je sais que c'était une petite blagounette, mais je pense qu'il vaut mieux éviter d'entretenir la confusion et je propose de supprimer.

Une explication de Ctrl+D sous Linux est ici :
https://unix.stackexchange.com/questions/110240/why-does-ctrl-d-eof-exit-the-shell/110248#110248

**Comment by pbischop** [comment]
Supprimé "caractères équivalents (pas de Ctrl-d ici ;-) )"

**Comment by nvansteenkiste** [comment]
je pense qu'il faut simplement expliquer que ctrl-d vide (flush) le tampon (buffer) en  lecture (https://stackoverflow.com/a/1516177). cela nécessite quelques phrases et un schéma d'explication mais les étudiants le comprennent sans soucis. j'ai l'habitude de leur expliquer en labo assembleur quand ils ont à coder un clone de cat.
dire que ctrl-d est eof n'est pas exact.

**Comment by YoungFrog** [comment]
Ils pourraient facilement tester avec cat, mais en java ça me parait  plus difficile de montrer ces nuances car Scanner.next() attend une fin de token pour retourner, donc un Ctrl+D n'a pas d'effet visible (sauf quand il signale EOF). Pour qu'ils comprennent bien cette explication, il faudra donc le faire dans un autre exercice (un exo lié à `cat` par exemple). En gros on pourrait
1. expliquer que Ctrl+d annonce la fin de fichier
2. montrer qu'en fait c'est pas vrai, mais que si Ctrl-D ne le fait pas, alors refaire Ctrl-D fonctionne.
3. revenir à la charge dans un autre exercice avec cat, où Ctrl+D a un effet visible (i.e. cat affiche tout ce qui a été tapé jusque là sans retour à la ligne).
4. revenir en java et voir pourquoi l'effet n'est pas visible avec Scanner.next()

**Comment by nvansteenkiste** [comment]
une note pour pas oublier : Ctrl-d c'est [EOT](https://en.wikipedia.org/wiki/End-of-Transmission_character) (end of transmission) et non EOF (end of file).

**Comment by nvansteenkiste** [comment]
merci pour tes remarques, YoungFrog. 

Ctrl-D demande une vidange du buffer, mais Scanner ne traite rien avant d'avoir rencontré un withe space. tout est clair, net et limpide maintenant.

**Comment by pbettens** [comment]
si tout est clair, je clos. inutile de conserver des issues ouvertes.

**Comment by nvansteenkiste** [comment]
lol

je pensais qu'on fermait les issues quand on avait intégré au td les remarques y afférentes. ce qui n'est pas le moins du monde le cas pour cette issue.

lol

**Comment by pbettens** [comment]
… ce serait bien que l'on se charge de fermer les issues.

**Comment by nvansteenkiste** [comment]
je comprends pierre. mais là c'est publié. cette issue sera réglée pour le milestone 2019-20. promis :-)

**Comment by YoungFrog** [comment]
Je ne vois plus ces lignes dans les nouveaux TDs. On mentionne cat et ctrl-d dans le td5 mais sans rentrer dans les détails.
