### ISSUE TITLE
javl / td11

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#166]
- tu utilises parfois l'impératif (écrivez) et parfois l'infinitif (intégrer)… 

- `s/qui parcours/qui parcourt/`

- en lisant l'exercice 8, je me dis que ce serait bien d'avoir une méthode `Dictionnaire.estDans(String mot)`… mais tu n'en parles pas dans la suite. je comprends ce que tu demandes aux exercices 9 et 10 mais ça « n'a plus rien à voir avec le fait d'avoir un joueur qui propose un mot ». non ?

**Comment by fservais-heb** [comment]
L'exercice 8 demande d'implémenter la méthode `boolean dansDictionnaire(String mot)`.
Cela demande de faire une recherche dans un tableau (de `String`), ce tableau contenant tous les mots 
est récupéré par l'appel `Dictionnaire.mots()`.

Tu voudrais changer cela par un simple appel à une méthode `estDans(String mot)` ? 
Ou bien l'énoncé n'est pas clair ?

**Comment by pbettens** [comment]
ok, en relisant, c'est clair. 
si tu as l'occasion, tu peux mettre les explications sur le jar dans un environnement spécial (notation ou autre) pour que l'explication se distingue du flux des exercices.

**Comment by fservais-heb** [comment]
Closed in  e309e1c0381e1b4b1eda15c3b15cade3e2dc2ccd
