### ISSUE TITLE
javl TD10 ex 4 : incohérence de l'énoncé

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#167]
L'énoncé dit "S'il y a plusieurs mots les plus longs, la méthode retournera n'importe lequel parmi ceux-ci. Dans l'exemple ci-dessus, la méthode retournera quick, brown, jumps"

Si on retourne n'importe lequel, il faut n'en retourner qu'un. Si on retourne tous ceux de la plus grande longueur, cela change assez bien l'algorithme (il faut nécessairement plusieurs parcours du tableau) et il faut reformuler la phrase.

"Plusieurs mots les plus longs" est une phrase qui n'a pas de sens.
J'écrirais aussi "S'il y a plusieurs mots de la plus grande longueur, la méthode retournera n'importe lequel parmi ceux-ci. Dans l'exemple ci-dessus, la méthode retournera par exemple jumps"

**Comment by YoungFrog** [comment]
Je lis "quick, brown /ou/ jumps", ce qui me semble correct. Ta formulation ne donne pas les autres possibilités, ce que je trouve dommage, mais sinon elle me convient aussi.

**Comment by npettiaux** [comment]
Effectivement, j'ai mal lu et n'ai pas vu le /ou/. J'ai compris que les 3 mots étaient retournés. Le début de la phrase est compréhensible mais pas très français.
