### ISSUE TITLE
vérification des (sha|md5)*sum

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#170]
https://github.com/HEB-ESI/dev1/blob/4800011c59af5c4c64c6211dcc61f9c3d378b2a0/labo-cli/labo-cli-08-ssh/labo-cli-08-ssh.tex#L406-L407

En relisant je me suis fait qq réflexions :

1. Étant donné la connexion un peu molle à l'ESI, et afin d'illustrer la remarque qui précède l'exercice, on pourrait leur faire télécharger l'ISO depuis une URL douteuse (mais locale au réseau ESI), puis leur faire vérifier ce fichier avec le hash récupéré sur le site officiel.

2. il y a deux fichiers debian*-netinst.iso.

3. on pourrait aussi mentionner l'option -c des divers outils `*sum` (mais j'aime bien l'idée qu'ils vérifient visuellement la première fois...)

4. ils ne savent sans doute pas ce qu'est une "iso".

**Comment by mcodutti** [comment]
Cette matière a disparu des tds.
