### ISSUE TITLE
envl / td 08 / ex 8 - option -C

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#173]
La commande `` ssh-keygen`` est déjà utilisée plutôt dans le TD mais ici on y ajoute l'option `` C``.
Une recherche dans le manuel permet de savoir qu'il s'agit d'un commentaire mais on se pose la question : " Commentaire pour qui / pourquoi ? Est-ce nécessaire ici ? Pq le mettre ici et pas avant ?"

**Comment by pbettens** [comment]
ce n'est « jamais » nécessaire. ça permet de mettre l'email de ton choix en fin de clé. j'aurais peut-être pu l'écrire à chaque fois.

**Comment by YoungFrog** [comment]
si j'ai bien compris, ce commentaire n'a aucune valeur en terme de sécurité : il est simplement ajouté à la clef publique mais n'est pas lié à la clef privée. C'est simplement une façon de se rappeler à quoi correspond la clef, si tu en as plusieurs...

**Comment by mcodutti** [comment]
Cette matière a disparu des tds.
