### ISSUE TITLE
envl / td 08 / 3.3 - connexion par échange de clés - incompréhension

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#175]
C'est pas vraiment une issue mais une question que je me pose.
Si on passe la clé publique qu'est-ce qui empêche un autre client de fournir la même clé publique lors d'une conenxion pour se faire passer pour moi ?
En plus, dans putty, l'option que j'ai trouvée (dans Connection/SSH/Auth) parle de ``PRIVATE key file for authentication``

**Comment by YoungFrog** [comment]
Tu donnes la clef publique (à linux1, gitlab ou qui tu veux), mais au moment de la connexion ssh ou putty devra utiliser ta clef privée pour s'authentifier. L'idée c'est que le serveur distant va chiffrer quelque chose avec la clef publique, et tu (càd ssh ou putty) seras le seul à pouvoir le déchiffrer car il faut la clef privée pour déchiffrer.

**Comment by mcodutti** [comment]
Merci pour les explications.
Le texte du TD me parait peu clair et trompeur.
Au lieu de 

> Lors de la connexion, le client enverra ses clés publiques et le serveur vérifiera s'il en possède une pour l'utilisateur ou l'utilisatrice donné·e. 
Si c'est le cas, l'authentification est faite.

J'écrirais qqchose comme

> Lors de la connexion, le serveur va chiffrer quelque chose avec la clé publique précédemment déposée par le client et lui envoyer. Le client devra le déchiffrer (avec sa clé privée) pour prouver son identité. 
S'il y parvient l'authentification est faite.

**Comment by YoungFrog** [comment]
La page man indique:

> The file ~/.ssh/authorized_keys lists the public keys that are permitted for logging in.  When the user logs in, the ssh program tells the server which key pair it would
>       like to use for authentication.  The client proves that it has access to the private key and the server checks that the corresponding public key is authorized to accept
>       the account.

La RFC contient quelques détails que je ne vais pas essayer de lire/comprendre maintenant...
https://tools.ietf.org/html/rfc4252#section-7

**Comment by YoungFrog** [comment]
@pbettens je te laisse ré-évaluer la situation - j'ai enlevé le wontfix en attendant.

**Comment by mcodutti** [comment]
Cette matière a disparu des tds
