### ISSUE TITLE
JAVL/TD11 Mot le plus long : liste de tous les mots (bonus 1)

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#178]
https://github.com/HEB-ESI/dev1/blob/7e14309bdee954f94a2e97e38613abc17a7b874e/labo-java/labo-java-11-mot-le-plus-long/labo-java-11-mot-le-plus-long.tex#L208-L217

Qu'est-ce qui est attendu ici ? La question m'a été posée par un étudiant, j'ai proposé d'utiliser ArrayList, mais la vérité est que je ne sais pas ce qu'on attend d'eux.

**Comment by nvansteenkiste** [comment]
ce que j'ai compris, c'est qu'il est demandé de fournir une méthode qui retourne un tableau de String dont le contenu est l'ensemble des mots du dictionnaire qui sont constitués uniquement des lettres du tableau de caractères en argument (où chaque caractère ne peut être utilisé qu'une seule fois) et qui sont les plus longs possibles.

je l'ai fait en 2 passes du dicto ci-dessous, mais y'a sûrement plus simple : 
```
public static String[] meilleursMots(char[] lettres) {
    // recherche de longueur maximale
    int maxSize = 0;
    int nbMots = 0;
    for (String mot : Dictionnaire.mots()) {
        int size = 0;
        if (verifierLettres(lettres, mot)) {
            size = mot.length();
        }
         if (size > maxSize) {
            // nouveau max
            maxSize = size;
            nbMots = 1;
        } else if (size == maxSize) {
            // nouveau mot de lgr max
            ++nbMots;
        }
    }

    // avec un conteneur dynamique, une seule lecture du dictionnaire
    // suffirait et serait facile à mettre en place. 
    // avec un vieux tableau, ça me semble plus lourd. je fais une 2e passe.
    // production du résultat
    String[] resultat = null;

    if (maxSize == 0) {
        // ici aucun mot possible
        resultat = new String[1];
        resultat[0] = "";
    } else {
        resultat = new String[nbMots];
        int i = 0;
        for (String mot : Dictionnaire.mots()) {
            if (mot.length() == maxSize && verifierLettres(lettres, mot)) {
                resultat[i++] = mot;
            }
        }
    }

    return resultat;
}
```

**Comment by YoungFrog** [comment]
ah oui j'ai pas pensé à compter le nombre lors de la première passe ! Merci :-)
