### ISSUE TITLE
Serialization vs simple écriture dans un fichier

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#179]
https://github.com/HEB-ESI/dev1/blob/4e04556d8bb6e0171d4ff0893b7e76d7cf64b5e7/labo-java/labo-java-13-exercice-recapitulatif/td13.tex#L55

Je propose de supprimer cette remarque car écrire ces données dans un fichier appelle forcément de pouvoir les relire... et il faut donc réfléchir au format dudit fichier. Java possède un mécanisme (l'interface java.io.Serializable) qui résout ce problème.
Cout ceci me semble encore hors de portée des étudiants pour un TD qui sera probablement réalisé seul chez eux comme entraînement.

**Comment by YoungFrog** [comment]
@SRexhep merci d'avoir màj sur poesi. Est-ce que tu pourrais aussi mettre à jour le .tex et pdf dans le dépôt git ? on pourra alors fermer cette issue.

**Comment by SRexhep** [comment]
C'est fait :-).
