### ISSUE TITLE
Cours- 5.3.2 - Introduction du ==

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#18]
Le `==` apparait pour la première fois dans un exemple.
Je vois que tout est explicité 30 pages plus loin mais il me semble qu'il faudrait au minimum une petite note ici.

**Comment by pbettens** [comment]
la remarque p53 ne suffit pas ? 

> Remarque Pour tester l’égalité, nous utilisons le symbole == afin de le différen-
cier du symbole = qui est le symbole de d’assignation. C’est la même chose en Java
et dans beaucoup d’autres langages.

**Comment by mcodutti** [comment]
Oui, ça suffit.
