### ISSUE TITLE
exercices 29 et 30

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#186]
https://github.com/HEB-ESI/dev1/blob/1627d6507d681a032f76d9fcda5f04722f6fc3c9/cours-developpement/syllabus/annexes/exercices-tracer.tex#L111-L128

Je ne comprends pas l'utilité des exercices 29 et 30 dans les exercices "tracer un algorithme". Les énoncés sont à peu de choses près identiques à ceux des exercices 11 et 17 avec le même titre (Allure et vitesse, Cote moyenne). Je peux les enlever ou ils ont une raison d'être ?

**Comment by pbettens** [comment]
hier, j'ai fait faire les exos 27 et 28 en montrant et faisant avec eux puis j'ai demandé de faire le 29 du début à la fin (avec une solution). 

on pourrait reformuler en mettant une référence vers les exercices 11 et 17. 

je m'en charge car je suis dessus pour l'instant.
