### ISSUE TITLE
Accent dans le nom d'une variable

### ISSUE THREAD

**Issue by asassoye** [HEB-ESI/dev1#188]
bonjour,
Je sais qu'en Java les accents sont permis dans les noms de variables, mais comme ceci est une introduction à la programmation en général, ne devrions-nous pas prendre comme convention de ne pas mettre d'accent dans les noms de variables, comme ce n'est pas possible dans la plupart des langages?

Exemple:
https://github.com/HEB-ESI/dev1/blob/381a01c4321e054ed6f959612d650f18fdfc0d30/cours-developpement/syllabus/annexes/exercices-tracer.tex#L81

**Comment by mcodutti** [comment]
Bonjour,
C'est un sujet qui est souvent débattu entre professeurs ;)
Nous avons décidé, en dev2, d'imposer l'anglais (code+javadoc).
En dev1, afin de ne pas cumuler les difficultés, nous avons décidé de permettre le français.
À partir de là, il me semble naturel d'orthographier correctement les noms de variables.
Par ex: une variable indiquant si un individu est âgé ou pas demandera moins d'effort cognitif au lecteur si elle est nommée `âgé` plutôt que `age`.
Il me semble que l'étudiant qui passera à un autre langage devra de toute façon se poser la question des contraintes liées à ce langage (longueur permise, caractères spéciaux...) ainsi que des conventions propres à ce langage (camelCase vs underscore...).
Faut-il se limiter à un sous-ensemble du possible le plus souvent transposable ou utiliser la richesse permise par le langage utilisé pour l'instant ? Le débat ne sera jamais clôt je pense.
Et, encore une fois, lorsqu'il passera à l'anglais (ce qui lui sera imposé après janvier), cette question là ne se posera plus.
Merci pour vos contributions à la correction du syllabus et des TDs.
M. Codutti.

**Comment by asassoye** [comment]
Merci pour votre réponse
