### ISSUE TITLE
envl td3 : l'option -d de javadoc drée le répertoire si il n'existe pas

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#196]
On dit que l'option -d de javadoc impose que le répertoire indiqué préexiste. Ce n'est PAS le cas. il est créé à la volée si il n'existe pas auparavant.

**Comment by YoungFrog** [comment]
From the man page :

> *       -d directory
>                Specifies the destination directory where the javadoc command
> *              saves the generated HTML files. If you omit the -d option, then
>                the files are saved to the current directory. The directory
>                value can be absolute or relative to the current working
>                directory. As of Java SE 1.4, the destination directory is
>                automatically created when the javadoc command runs.
> 

je supprime donc la remarque du TD.
