### ISSUE TITLE
ajout de tous les types java 

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#197]
tous les types (byet, short, int…) ne sont pas présentés dans le syllabus alors que l'on suppose qu'ils sont connus en dev2. 

je propose d'ajouter un complément à ce sujet dans le syllabus.

**Comment by YoungFrog** [comment]
Ils sont dans cours-developpement/syllabus/base/module.tex -- faut-il autre chose ?

**Comment by pbettens** [comment]
oui, voir anciens slides dev1 à partir du 114 (p131). 

- citer tous les types
- les intervalles
- les littéraux

**Comment by YoungFrog** [comment]
ok les types et les intervalles sont cités dans un petit tableau, mais effectivement pas toutes les façons d'écrire des littéraux.

On pourrait en profiter pour corriger les explications sur "char" : un char n'est pas (plus) exactement de l'UTF16 car UTF16 est à longueur variable. Des éléments d'explication se trouvent ici : https://stackoverflow.com/questions/13112435/how-does-java-store-utf-16-characters-in-its-16-bit-char-type et un rant se trouve ici https://codeahoy.com/2016/05/08/the-char-type-in-java-is-broken/

**Comment by pbettens** [comment]
à l'époque du slide, c'était sous-entendu que char ne prenait que le sous-ensemble utf-16 des valeurs codées sur 16 bits et évidemment pas les autres. je parlerai par contre explicitement de BMP. 

merci pour les liens

**Comment by pbettens** [comment]
voilà, j'ai revu un peu le chapitre modules pour reporter une partie dans le complément types que je viens d'ajouter. je vous invite à relie et me faire vos commentaires. 

je publierai ensuite ;-)

**Comment by YoungFrog** [comment]
J'ai modifié quelques (imho) trivialités (fafbdd6)

Je voudrais aussi faire noter que peu importe la base d'un littéral entier, le résultat est un int (ou un long), et on ne peut plus les distinguer. Ceci n'est à mon avis pas clair à partir des noms des variables choisis (p.ex. myInt vs myOctalInt). Je me disais, plutôt que des variables, plutôt faire un affichage avec println et montrer le résultat ?

la notation \u0000 \uffff n'est probablement pas claire pour le lecteur (m/f/x). On pourrait utiliser la syntaxe java tout juste introduite ?

dans https://fr.wikipedia.org/wiki/Guillemet#Codage les single quote se traduisent par guillemet apostrophe.

échapper des caractères : n'est-il pas étrange de dire que les caractères ont leur signification habituelle en précisant qu'un a est un a, mais qu'un ' n'est pas un ' ? je ne pense pas qu'on a la même définition de "signification habituelle" ;-) Je reprendrais la terminologie de ton tableau "sens premier" "sens second".

pour ieee754 j'enlèverais les indices 2 dans la formule "signe mantisse_2 2^exposant_2"

**Comment by pbettens** [comment]
merci pour les corrections.

1/ j'ai ajouté une remarque plutôt que de faire des sout pour toutes les variables. comme j'utilise toujours la même quantité (100), je trouve que ça aide à la compréhension. 

2/ je ne comprends pas bien ce que tu proposes. j'écris `\u0000` pour la plus petite valeur 16 bits et `\uffff` pour la plus grande. (je ne sais par contre pas pq je mets un \u ;-) 

3/ vivement que je doive traduire back quote `: *guillemet-virgule supérieur culbuté* ;-) 

    corrigé

4/ fait

5/ fait

**Comment by pbettens** [comment]
j'ai déposé le pdf, c'est bon pour vous si on publie ?

**Comment by YoungFrog** [comment]
@pbettens pour \uffff je proposais d'utiliser 0xffff à la place.
