### ISSUE TITLE
envl td5 : ex9 supprimer "il est possible que"

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#199]
dans l'exercice 9, il est écrit "il est possible que la commande tente d'accéder à des sous-dossiers". 
Ce n'est pas seulement possible, c'est ce qui se passe. Il faudrait par exemple écrire "Si on utilise la commande find pour chercher un fichier, celle-ci tente d'accéder ..."

**Comment by YoungFrog** [comment]
il est écrit ensuite "pour lesquels vous n'avez pas les droits", ce qui rend la phrase pertinente. Je pense que tu as simplement mal lu donc je clos, mais si tu penses qu'il faut modifier la phrase je t'invite rouvrir voire à modifier le td.

**Comment by YoungFrog** [comment]
finalement j'ai pensé à une simplification triviale qui devrait éviter le malentendu cf 71609ac76be55df7ab0fbb892bdbeea8d37b3a48
