### ISSUE TITLE
l'option pour afficher la date de dernière modif

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#200]
J'ai été perturbé hier face à cet exercice :

https://github.com/HEB-ESI/dev1/blob/f47263eb0c96a9e5cdb53d3d20f7ad9141f7b6f0/labo-env/02-linuxII/dev1-envl-02-linuxII.tex#L437-L439

Ce qui est perturbant est que l'information par défaut dans "ls -l" est précisément la date de sa dernière modification. Donc l'option à trouver serait "-l" ? Mais cette information spécifique se trouve difficilement : dans "ls --help" et "man ls", il faut aller voir du côté de l'option "--time" où l'info est donnée de façon laconique. Si on veut une info plus complète il faut consulter "info ls" sous le menu "What information is listed".

A contrario si on cherche "last modification" dans la page man, on tombe sur "-c". Cette option va modifier "-l" pour afficher le ctime, ce qui n'est en fait pas l'information demandée.

Pour avoir une information complète sur ce que sont le mtime (l'info par défaut avec -l) et le ctime (avec -l -c), on peut aussi aller voir :

>  info '(coreutils)File timestamps'

mais c'est probablement un peu loin par rapport aux objectifs du TDs ?

Tout ça pour dire que je pense qu'il vaut mieux demander autre chose à chercher dans la doc :-)

**Comment by npettiaux** [comment]
très juste. Il manque aussi le nom de la commande (ls) avant "pouvait".
