### ISSUE TITLE
envl tf1 ex6 

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#201]
q1. "Créer un nom de fichier ..." n'a pas de sens. C'est "créer un fichier dont le nom contient une espace" (en typographie, espace est féminin, alors que dans les autres cas, le mot est masculin)

Je ne trouve pas dans les pages de manuel comment créer un fichier dont le nom contient un espace. C'est une recherche sur le net qui m'a donné le réponse.

q2 - q4 : on demande des questions qui ne sont pas évidentes pour les étudiants qui ne connaissent pas encore la récursivité !

**Comment by YoungFrog** [comment]
pour la q1 je pense que tu pinailles un peu, mais je modifie

pour les q2-q4, je ne pense pas que connaître la récursivité les aiderait.

pour toutes les questions, je crois qu'une recherche sur le net donne généralement la réponse assez rapidement. Le début de la question indique clairement que c'est une chose à tenter.
