### ISSUE TITLE
envl td2 ex2 et ex6 questions mal posées ?

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#204]
Dans ces questions, il n'est pas indiqué dans quel répertoire est le fichier welcome. Pourquoi supposer qu'il est dans le répertoire home de l'utilisateur ? 
En tant que telles, les questions apparaissent comme mal posées.

**Comment by YoungFrog** [comment]
dans la Q2 il est écrit qu'on est supposé se trouver dans notre home.
dans la Q6 ce n'est pas rappelé. je vais arranger cela.
