### ISSUE TITLE
envl / td2 / ex8 : pas clair et pas testable à ce moment

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#205]
On demande aux étudiants de chercher une option qui permet de voir les tailles de fichiers sous un format plus lisible. Cette question n'est pas évidente à mon avis, d'autant plus qu'à ce moment dans les répertoires des étudiants il n'y a que de petits fichiers.

On pourrait leur suggérer d'utiliser la commande pour voir les fichiers de /usr/bin pour voir la différence par rapport à ls -l seul

Je suppose qu'il est attendu qu'ils trouvent : 

       -h, --human-readable
              with -l and -s, print sizes like 1K 234M 2G etc.

**Comment by YoungFrog** [comment]
J'ai eu le même réflexe, donc je suis favorable à ta suggestion.
