### ISSUE TITLE
où est défini ArrayDeclarationExpression ?

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#206]
https://github.com/HEB-ESI/dev1/blob/497581310436f99d0a83a713b24f8318793b79db/cours-developpement/syllabus/tableau/tableau.tex#L279-L280

Je ne retrouve pas cette règle dans les JLS que j'ai consultées (jls3.pdf, jls7.pdf, jls13.pdf). Google ne semble pas connaître non plus. Du coup je commence à douter, d'autant que une "ArrayDeclaration" ne me semble pas être une "Expression"... serait-ce de la pure invention ? ou une jls qui date du temps que les moins de 0x20 ans ne peuvent pas connaître ?)

FTR, jls8 contient:

```
LocalVariableDeclaration:
{VariableModifier} UnannType VariableDeclaratorList
```

où
-  UnannType (unannotated type) permet de retrouver le morceau "Type []", et
-  "VariableDeclaratorList" permet de retrouver "Identifier".

```
UnannType:
UnannPrimitiveType
UnannReferenceType

UnannReferenceType:
UnannClassOrInterfaceType
UnannTypeVariable
UnannArrayType

UnannArrayType:
UnannPrimitiveType Dims
UnannClassOrInterfaceType Dims
UnannTypeVariable Dims
```

```
VariableDeclaratorList:
VariableDeclarator { , VariableDeclarator}
VariableDeclarator:
VariableDeclaratorId [ = VariableInitializer]
VariableDeclaratorId
VariableDeclaratorId:
Identifier [Dims]
```

**Comment by pbettens** [comment]
j'ai sans doute écrit ça pour insister sur déclaration / création / initialisation. 
je ne me rappelle plus très bien mais je ne trouve pas non plus dans jls… et je n'ai pas écrit avant « voici la grammaire java » ;-) 

ce serait mieux de : 

- écrire que c'est une grammaire simplifiée (qui n'est pas dans la grammaire officielle)
- remplacer *ArrayDeclarationExpression* par *ArrayDeclarationStatement* et ajouter un `;` à la fin. 

Ce serait bien ?

**Comment by YoungFrog** [comment]
bien pour moi. Le ';' n'est pas fondamental : pour les ForStatement et quelques autres on en n'a pas mis.

faut-il complètement passer sous silence l'existence d'une déclaration du genre "int foo[];" ?

**Comment by pbettens** [comment]
*faut-il complètement passer sous silence l'existence d'une déclaration du genre "int foo[];" ?*

oui, je n'écrirais rien à ce sujet.
