### ISSUE TITLE
Cohérence entre cours et labos

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#21]
Je prend par exemple la notion de variable.
- Au labo, elle apparaît au TD 1, sans aucune forme d'explication.
- Dans le cours, elle apparait au chapitre 5 !
Comment on gère ça concrètement ?

**Comment by pbettens** [comment]
les labos se font du td1 au td11 (ou 12). dans l'ordre. 

le syllabus est un support qui se veut cohérent (j'ai bien lu les autres issues).

le planning détaillé du cours précisera les matières à aborder à chaque séance. c'est ce planning qui déterminera l'ordre. ce planning détaillé du cours est encore à écrire (voir https://docs.google.com/spreadsheets/d/1jKG3Xzm0Cb8swE8AaicL3XP77g1gJT5s_cJo0Vkxw4I/edit#gid=0)…

**Comment by pbettens** [comment]
je clos suite à notre discussion de… heu… vendredi.
