### ISSUE TITLE
Algorithme  erroné - subscribe dans un tableau trié 

### ISSUE THREAD

**Issue by fservais-heb** [HEB-ESI/dev1#211]
deux erreurs:

- `shiftRight(registred,pos, nRegistered);` --> `shiftRight(registred,pos, nRegistered-1);`
- doit retourner un int pour le nRegistered

**Comment by pbettens** [comment]
n'est-ce pas ce qui est écrit dans l'errata
https://paste.esigoto.info/?6e098820c5ad54ca#ZCHtC9dkJ7MosHrWvZxq70b8RccOI6Aw272pY459DlY=

… et dans le commit c54976a

**Comment by YoungFrog** [comment]
Fixed in 8742e1abb2fd460881d4b90be375191728b3ff53
