### ISSUE TITLE
Algorihme erroné - recherche dichotomique

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#212]
Plusieurs erreurs dans cet algo : 
1. 2 erreurs qui s'annulent mais qui ne sont pas cohérentes avec les exemples donnés avant
a) `rightIndex = myArray.length` devarit s'écrire `rightIndex = myArray.length - 1`
b) `leftIndex < rightIndex` devrait s'écrire `leftIndex <= rightIndex`
1. Quand on ne trouve pas, on retourne -1 alors que traditionellement, on retourne la position où on aurait du le trouver/on pourrait l'insérer. Pour ça, changer le `return -1` en `return leftIndex` (mais c'est vrai que ça prend du temps pour être convaincu de c'est bien `leftIndex`)

**Comment by nvansteenkiste** [comment]
pour le 1. je n'en sais rien. 

pour le 2. m'étonne un peu. je ne sais pas ce que _traditionnellement_ veut dire, mais en C, C++ ou Java, c'est une valeur d'index impossible (négative) ou une valeur sentinelle de pointeur / itérateur / référence qui est retournée. ça permet de rapidement savoir si l'élément y est ou non :-)

par exemple en [Java](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/Collections.html#binarySearch(java.util.List,T)) c'est quelque chose du genre -leftIndex -1 qui est retourné.

**Comment by mcodutti** [comment]
OK pour le 2.
Mon point était qu'en plus de savoir si la valeur y est ou pas, la méthode donne une info sur l'endroit où la mettre.
Dans mon souvenir, dans les anciennes version du syllabus, on retournait un booléen et un paramètre en sortie donnait la position où il était si trouvé ou la position où le mettre si pas trouvé.
Je n'avais pas retenu cette idée de négatif dans la version Java, un peu tordue mais soit.

**Comment by pbettens** [comment]
avant on retournait deux valeurs puisque c'était un algo. maintenant que je donne l'exemple en java, je ne peux retourner qu'une seule valeur. 

c'est la première fois que je vois le `-leftIndex - 1` tu as des liens pour « montrer que c'est l'habitude » ?

**Comment by nvansteenkiste** [comment]
je n'ai jamais dit que retourner ```-leftIndex - 1``` est l'habitude. j'ai écrit que :

> en C, C++ ou Java, c'est une valeur d'index impossible (négative) ou une valeur sentinelle de pointeur / itérateur / référence qui est retournée.

pour ce qui concerne Java et la valeur spécifique ```-leftIndex - 1```, je t'invite à cliquer le lien que j'ai fourni dans ma réponse initiale il y a une dizaine de jours ;)

**Comment by pbettens** [comment]
damned ! tu avais caché un lien ;-) 
(je sais que tu ne l'avais pas caché et que je ne l'ai pas vu). 

sérieusement, si oracle le fait, c'est que c'est « bien ».

**Comment by nvansteenkiste** [comment]
sinon, avant la remarque de Marco, j'ignorais qu'en Java l'index retourné en cas d'absence de la valeur recherchée dans la collection est ```-leftIndex - 1```. juste que je trouvais bizarre de retourner une position _plausible_ alors que la valeur n'y est pas.

**Comment by YoungFrog** [comment]
This was fixed by 05701545dbc4d89fe63bd533887825145c0d3354
