### ISSUE TITLE
 "piper" le résultat d'un ls est rarement bon

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#214]
https://github.com/HEB-ESI/dev1/blob/795f94f981d12481e6b564b9fa9803de25a0f15d/labo-env/06-linuxIV/dev1-envl-06-linuxIV.tex#L263

Dans cette ligne et à d'autres endroits, on dit (parfois implicitement) qu'une solution est de faire "ls | des-commandes". Même si ce n'est qu'un exemple pour illustrer le principe des redirections, cela a un effet de bord néfaste : cela donne l'habitude de parser "ls", ce qui est une très mauvaise pratique (voir par exemple https://mywiki.wooledge.org/ParsingLs)

Il faudrait à mon avis :
- a minima, avertir du danger
- idéalement, à chaque fois montrer une bonne manière de faire ce qu'on demande.

(Par exemple, à la place du cut ci-dessus, on pourrait faire 

> for filename in *; do printf "%s\n" "${filename%.*}"; done

ce qui a aussi l'avantage de résoudre le souci d'un fichier qui s'appellerait "my.bashrc.gz", pour lequel on s'attend sans doute à obtenir "my.bashrc" plutôt que "my". Cela dit qui voudrait  afficher une liste de ses fichiers sans leur extension ?)

**Comment by antegallya** [comment]
Je n'ai rien à voir là dedans, mais comme je le vois passer :
quid d'utiliser `ls -b1` avec le footnote qui explique pourquoi le `-b1` ?

**Comment by YoungFrog** [comment]
Pourquoi pas, tant qu'on garde le message "ls c'est pour l'humain, il ne faut pas parser ls"
