### ISSUE TITLE
Atteinte des objectifs

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#22]
Parmi les critiques que j'ai entendues l'année passée, revenaient souvent : 
- Ils doivent apprendre le lda ET le JAVA
- Ils doivent faire des exercices sur papier, trop peu concrets
En quoi, la formule actuelle du cours résout ces 2 problèmes ?
Il me semble que le cours et les TDs ont été écrits indépendamment, sans concertation.
Par exemple, la plupart des exercices du syllabus ne sont pas demandés au labo.
Ils vont rester des exercices sur papier ?

**Comment by npettiaux** [comment]
J'ai le même sentiment que Marco.

**Comment by fservais-heb** [comment]
Je partage ces inquiétudes. 

- "ils doivent apprendre le lda ET java" -  l'idée retenue après discussion en juin est de donner aux étudiants plusieurs outils: organigramme, pseudo-code et java. Personnellement je ne suis pas chaud pour cette formule et j'aurais laissé tomber le pseudo code et les organigrammes (éventuellement utiliser des organigrammes au début pour expliquer la sémantique des instructions ou illustrer grossièrement le déroulement d'un algorithme). Pour moi le cours devrait se concentrer sur java et l'algorithmique, et si/lorsqu'une production de code est demandée sur papier que ce soit de la syntaxe java avec quelques simplifications acceptées: System.out.xxx -> print, pas de classe, pas de main, readInt, readLine etc. Chacun a son avis et sa vision sur la question, on devrait relancer la réflexion pour la v2 et voir ce qu'on peut faire pour le v1 mais il est tard. De toute façon quand on passera à Python toute cette discussion n'aura plus lieu d'être ;-)
- "Exercice sur papier trop peu concret" - ma vision des choses est la suivante
   -  les 4 premières semaines servent à se familiariser avec la syntaxe et la sémantique d'un langage de programmation (java), cela rend concret les outils de résolution des problèmes. Le type d'exercices en classe (cours théorique) est de la lecture de programme: "que va afficher ce bout de code" ou encore: "quelles sont les données de ce problème (input) quelles sont les productions attendues (output)" 
   - les semaines suivantes on commence de l'algorithmique et là les étudiants peuvent produire du code (simplifié). Par exemple: `int max(int a, int b) { int max = a; if(a<b) {max = b;} return max;}` C'est plus concret car ils se sont familiarisé avec les outils.
    - j'aurais aimé que les étudiants se familiarisent avec l'analyse basique de programme: complexité et correction. Mais je sens que je ne vais pas être suivi sur ce point :-)
- "Les TDs et les cours ont été conçu indépendamment" - Le cours n'est pas encore vraiment conçu :-) tu parles sans doute du syllabus. Par soucis pratique l'idée a été de retravailler le syllabus existant fruit de plusieurs années de travail. Ce syllabus est un support et pas une table des matières/agenda du cours. Il y a effectivement du travail à faire pour synchroniser le cours et les TDs. C'était là discussion qu'on a eu la semaine dernière lors de l'élaboration du planning du cours.

Concrètement on peut dès maintenant sélectionner les exercices qui seront fait au cours ET au labos.

**Comment by mcodutti** [comment]
> les 4 premières semaines servent à se familiariser avec la syntaxe [...] Le type d'exercices en classe (cours théorique) est de la lecture de programme [...] les semaines suivantes on commence de l'algorithmique et là les étudiants peuvent produire du code (simplifié)

Pourquoi on estime qu'au cours, il faut 4 semaines avant de pouvoir produire du code mais qu'au labo ils doivent déjà écrire du code dès le TD2 ? Je ne vois pas la cohérence et ça m'inquiète parce que ça commence quand même dans 10 jours et je ne vois toujours pas comment je vais pouvoir me débrouiller au cours avec seulement 4h/semaine.

**Comment by npettiaux** [comment]
Marco écrit bien mon désarroi.

**Comment by YoungFrog** [comment]
Ce que j'ai compris de la réponse de @fservais-heb  : 
Ils peuvent écrire du code dès le premier jour, il suffit de leur montrer comment.
Mais écrire du code en autonomie doit attendre quelques semaines.

Pour revenir à l'issue:
- Pour le LDA, je parle pour moi : je ne jugerai plus aucun élément de syntaxe du LDA comme j'ai pu le faire notamment au Q1. Je me fourvoyais pensant que j'étais "obligé" de procéder de la sorte. J'ai sûrement passé 50% de mon temps en algo à pinailler sur le LDA, à montrer que telle ou telle construction devait s'écrire différemment. Et je me suis interdit d'écrire le moindre bout de Java. En ce sens, pour moi cet aspect là est arrangé. Je ferai du (pas "la") Java à tous les cours.
- Pour les exercices sur papier : je suis favorable à faire des exos en grande partie sur papier, même si le but est à la fin de pouvoir écrire du code. Tant qu'on n'écrit pas du LDA dans l'unique but d'avoir du LDA.
- Pour la cohérence : c'est clairement un point à travailler. Le fait que le cours et les labos soient donnés par des personnes différentes n'aide pas. Une coordination des intervenants avec un mécanisme de rétroaction devrait idéalement se mettre en place.

Tout cela étant dit, je me permets de fermer l'issue car je ne vois pas de levier d'action immédiat. La discussion peut cependant continuer...

**Comment by fservais-heb** [comment]
Ne devrait-on pas la laisser ouverte afin d'y revenir pour la v2 (2019-2020) ?
