### ISSUE TITLE
TD1 - Phrases énigmatiques

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#23]
Certaines phrases / expressions seront probablement énigmatiques pour les étudiants. Il faudrait les détailler oralement ou par écrit.

1. `le dossier contenant les sources de votre projet`. La notion de "source" ne voudra rien dire pour eux.

1. `Le texte entre guillemets sera affiché sur la sortie standard`. Le terme "sortie standard" tombe de nulle part et ne va pas leur parler.

Celle-ci l'est pour moi : `N’hésitez pas à tester les codes présentées dans les TDs sur votre machine.`. Qu'est-ce qu'on veut dire part là ?

**Comment by npettiaux** [comment]
à propos des sources. Effectivement, cela fait référence sans doute au cours dans lequel cela aura été dit. On veut sans doute dire ici "Faites un clic droit sur <Source package> . Ceci permettra de définir l'endroit dans la structure du stockage de votre projet où seront mis les fichiers ainsi que le package Java" (ouille c'est difficile d'être clair car effectivement, il y a beaucoup de choses qui arrivent en même temps)
