### ISSUE TITLE
TD 1 : division par zéro

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#32]
Dans l'exercice 5 du TD1, on termine par une division par 0 pour des réels et pour des entiers. Dans le premier cas, java indique Infinity et continue. Dans le second cas, il s'agit d'une Exception qui arrête l'exécution du programme. Je me demande si il ne faut pas être plus explicite et le dire dans l'énoncé du TD plutôt que le laisser à l'examen des étudiants

**Comment by fservais-heb** [comment]
Je propose de laisser tel quel.
ok ?

**Comment by npettiaux** [comment]
Il faut qu'ils essayent en mettant des lignes après l'exception pour se rendre compte que ce n'est pas exécuté.

**Comment by fservais-heb** [comment]
Oui, le genre de chose qu'ils essayeront par eux mêmes.
On ne doit pas tout contrôler dans leur apprentissage, je suis sûr que tu seras d'accord avec moi sur ce point ! :-)

**Comment by YoungFrog** [comment]
J'ajouterais une phrase dans le sens de NPX: "Essayez d'afficher encore une expression après la dernière. Que se passe-t-il ?"
Quelle que soit la décision, je crois qu'on pourra ensuite fermer l'issue.

**Comment by YoungFrog** [comment]
Le TD est publié, on verra à l'usage.
