### ISSUE TITLE
Syllabus : 7.5 switch sans break

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#34]
Page 77, dans le selon-que en java, il est écrit 
switch (dayNumber) {
 case 1:
 dayName = "lundi";
 case 2:
 dayName = "mardi";
case 3:
dayName = "mercredi";
case 4:
dayName = "jeudi";
case 5:
dayName = "vendredi";
case 6:
dayName = "samedi";
case 7:
dayName = "dimanche";
}

sans break entre les lignes. J'avais le souvenir, comme décrit https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html qu'il faut des breaks sinon lors d'un choix (ex dayNumber=1), on termine quand même avec dayName valant "dimanche"

**Comment by pbettens** [comment]
oups ! bien vu. merci.
