### ISSUE TITLE
Installation de Netbeans

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#35]
Est-ce qu'on explique quelque part comment installer correctement un Netbeans à la maison ?
Même version que nous avec un Java compatible.

**Comment by nvansteenkiste** [comment]
je verrais bien ça dans le td1 d'envl.

**Comment by YoungFrog** [comment]
Je pense que l'installation sur les machines personnelles ne peut pas vraiment faire partie des labos (qui se font sur les machines de l'école). Je proposerais donc plutôt un document externe, référencé dans le cours et dans les labos, et les étudiants feraient cela sur base volontaire.

Cela dit, je ne m'oppose pas, loin de là, à ce que ce soit intégré aux labos ENVL.

**Comment by pbettens** [comment]
si c'est un document externe, c'est bien que l'on y fasse référence dans le td envl1. ce document peut faire partie les références proposées pour dev1.

**Comment by YoungFrog** [comment]
J'ai ajouté un Wiki, actuellement caché pour les étudiants, placé dans la section Cours de développement.
https://poesi.esi-bru.be/mod/wiki/view.php?id=1061

Pierre je te laisse décider de l'afficher ou non, et à quel endroit (je ne suis par exemple pas parvenu à le placer sous "Ressources" avec le même décalage que les autres ressources...)

**Comment by pbettens** [comment]
fait
