### ISSUE TITLE
Suppression des types en "algo"

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#36]
https://github.com/HEB-ESI/dev1/blob/64e720cde572a7680148326649d934511aa67931/cours-developpement/syllabus/base/specifier.tex#L169-L183

Pouvons nous supprimer la première colonne de ce tableau ? J'aimerais beaucoup ne pas avoir à lister explicitement les types en pseudocode.

**Comment by pbettens** [comment]
j'attends que vous ayez lu la référence pseudocode avant de modifier.

**Comment by YoungFrog** [comment]
Si c'est ok je peux le faire.
Si c'est pas ok on peut fermer/repousser à l'année prochaine ?
