### ISSUE TITLE
8.3.2 paramètres en entrée-sortie : algo et java ?

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#37]
à la page 83, section 8.3.2 on décrit les paramètres en entrée-sortie en algo avec un exemple

1: algorithm valAbsolue(nb↓↑ : réel)
if nb<0 then
nb = -nb

 algorithm test()
réel température
température = -12.5
valAbsolue(température)
print température

mais pas le correspondant en java. 

Plus loin, dans 8.4.3 (paramètres en java), on décrit les types références (8.4.2) et comment les utiliser en java. On commence par dire "Les paramètres en Java se passent par valeur. En ce sens, c’est équivalent aux paramètres en entrée." puis 
"Il n’y a pas de paramètre en entrée/sortie en Java puisque tous les passages de
paramètres se font par valeur. Si le paramètre est de type référence, la valeur que
reçoit la méthode est la valeur de la référence. Même s’il n’est pas possible de modifier
le paramètre reçu, il sera possible de modifier l’objet ou le tableau référencé par
la valeur reçue en paramètre. En ce sens, c’est un peu un passage de paramètre en
entrée/sortie." mais sans dire comment le cas de l'algorithme valAbsolue sera traduit en java. Il est en effet clair que la valeur nb passée en paramètre sera de type primitif double (voir le tableau page 27 où les correspondances algo-java sont données) mais donc elle ne peut pas être en entrée-sortie.

**Comment by pbettens** [comment]
exact, j'ajoute une remarque: 

{Remarque} Nous verrons dans la section
\ref{primitif-reference} que le langage Java ne permet pas de traduire
ces algorithmes en l'état.
