### ISSUE TITLE
td git : 2.5.2  point 3 envoyer sur gitlab

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#38]
Il me semble qu'il faut indiquer aux étudiants de faire 
git add test.sh
git commit -m "petit fichier de test"

avant le point 3 envoyer sur gitlab
=======
D'autre part, ici gitlab veut dire git.esi-bru.be. Ce n'est pas évident que c'est l'nstance de esi de gitlab qu'il faut utiliser car il y a aussi gitlab.com

**Comment by YoungFrog** [comment]
Il est écrit que les étudiants doivent committer. Je n'ai pas rappelé comment faire, ils devraient le savoir à ce moment là du TD, mais je rajoute les instructions sous forme de "réponse" pour les distraits.

Pour Gitlab: je ne parle à aucun moment d'une autre instance Gitlab que la notre,donc je pensais que c'était clair ; mais je rajoute l'URL entre parenthèse pour clarifier encore.

Merci.
