### ISSUE TITLE
javadoc

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#4]
introduire la javadoc et l'ajouter à toutes les méthodes qui suivent. 

quand ?   
peut-être au chapitre 11 algorithmes d'insertion et de recherche

**Comment by YoungFrog** [comment]
Hm ça serait bien de le faire je pense, est-ce réaliste ? Je vous avouerai n'avoir jamais écrit une javadoc de ma vie.

**Comment by pbettens** [comment]
ce ne sera par pour cette année.

**Comment by pbettens** [comment]
en commençant à rédiger, j’ai trouvé ces deux superbes liens : 

- http://valvassori.free.fr/dave_small/heresie1.php3
- http://valvassori.free.fr/dave_small/heresie2.php3

**Comment by YoungFrog** [comment]
L'auteur semble avoir une certaine rancoeur envers certaines personnes, mais quel est le lien avec la javadoc ? Faut-il abandonner et prendre l'assembleur comme premier langage ?

**Comment by pbettens** [comment]
et voilà ! 
il reste à relire avant que je ne publie.

**Comment by pbettens** [comment]
j'ai essayé de tenir compte de vos commentaires et je publie. 
bon we ;-)

**Comment by YoungFrog** [comment]
merci pour le document. Je n'ai pas eu l'occasion de commenter avant publication, mais voici tout de même: 

1. Dans la règle de style numéro 8 ("omettre le sujet") on parle ici de description de variable : est-ce une partie de la javadoc?
2. J'ajouterais une règle : écrire la javadoc en anglais ? en tout cas tous tes exemples sont en anglais. Pour info, en CAI1, on va leur demander de produire de la documentation en anglais ; ça aurait du sens et une certaine cohérence de le faire en DEV1
3. Pour la commande javadoc + find, les quotes autour de *.java ne sont pas des "straight quotes", du coup ça marche pas en faisant copier-coller. on pourrait utiliser `\textquotesingle` mais...
4. ... en pratique je propose de remplacer ce javadoc+find par `javadoc -d doc -charset utf-8 -sourcepath path/to/src -subpackages package` qui me semble plus dans l'esprit de l'outil. On peut ajouter des chemins et des packages en séparant par des ":"

**Comment by pbettens** [comment]
1. je voyais ça pour la description des paramètres dans le cas de la javadoc. je mets variables car la règle est plus large. 

2. pour l'anglais, je mets souvent en anglais mais je sais que tous les collègues ne sont pas forcément d'accord avec l'anglais en dev1. je peux écrire « dans la mesure du possible »

3. que ça ne fonctionne pas en faisant un copier-coller m'inquiète fort peu ;-) 

4. … et j'ajoute ta commande comme il reste de la place.

**Comment by pbettens** [comment]
… en fait, iels n'ont pas encore vu la notion de package. normalement, quand  `javadoc` « cherche » il faut que l'arborescence corresponde aux noms de packages

**Comment by YoungFrog** [comment]
ok. Si on laisse la version avec find, je propose d'ajouter une remarque qu'elle ne fonctionnera pas si il y a des symboles spéciaux dans certains noms de dossiers ou de fichiers, comme des espaces (mais celui ou celle qui met des espaces dans ses noms de répertoires ne mérite pas vraiment que ça marche, donc c'est ok.)
