### ISSUE TITLE
td git : exécution de gitk

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#40]
Je ne comprends pas  où  les étudiants exécutent gitk : linux1 ou sur la machine sur laquelle ils utilisent git-bash ?

**Comment by YoungFrog** [comment]
C'est sur Git Bash, parce que depuis linux1 ils n'ont pas accès à un serveur X qui leur permettrait de lancer gitk.

**Comment by YoungFrog** [comment]
Je pense que le contexte est assez clair sur ce point s'ils suivent le TD. Si tu penses le contraire n'hésite pas à rouvrir/proposer une modif.
