### ISSUE TITLE
td git : connaissance de vim

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/dev1#41]
Dasns 2.7.2 Fusion : merge on dit "le programme vim se lance ..." Ceci suppose que les étudiants aient été familiarisés avec vim ce qui n'est à ma connaissance plus le cas.

**Comment by YoungFrog** [comment]
Je ne le suppose pas, mais c'est vrai que ç'eut été mieux. Là ils peuvent juste taper `:x` et oublier rapidement cette douloureuse expérience ;)
Plus sérieusement, tu penses qu'il faut rajouter des explications ? De quel genre ?
De toute façon un jour ou l'autre ils lanceront une commande qui appellera vi(m) automatiquement et ils devront trouver un moyen de sortir ;)

**Comment by pbettens** [comment]
on peut afficher des feuilles dans chaque labo avec en très grand **«:x»**

**Comment by pbettens** [comment]
je pense que ce sera fait dans un autre td envl.
