### ISSUE TITLE
ENVL/td01 : quels exercices préparatoires ?

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#45]
https://github.com/HEB-ESI/dev1/blob/eb0fab82136e3eec6371665c30904680ef2a2443/labo-cli/labo-cli-01-introduction/labo-cli-01.tex#L674

ne faudrait-il pas préciser qu'il s'agit du TD02-prépa ?

**Comment by fservais-heb** [comment]
y a aussi le TD03-prépa :-)
