### ISSUE TITLE
JAVL - TD6  exercice incompatibilité des types

### ISSUE THREAD

**Issue by fservais-heb** [HEB-ESI/dev1#47]
Ajouter un/des exercices explicitant des erreurs de compilation:
- type de retour incompatible
- type de paramètre incompatible

**Comment by YoungFrog** [comment]
Je n'ai pas jusqu'à présent (après mon premier labo, donc) ressenti ce besoin d'ajouter de tels exercices. @fservais-heb  Tu trouves que ça a manqué à tes étudiants ?

**Comment by fservais-heb** [comment]
@pbettens je ne vois pas en quoi 8f6de83 ferme cette issue.
@YoungFrog Je trouve que ça manque :)

**Comment by pbettens** [comment]
j'ai rajouté un exercice. si tu trouves qu'il en faut plus, tu peux réouvrir et en proposer ici. 

    \begin{Exercice}{Erreurs de types}
        Dans votre méthode main, faites les appels suivants~:
        \begin{itemize}
            \item \texttt{String résultat = premièreLettre("Hello");}
            \item \texttt{char caractère = dernièreLettre(123);}
        \end{itemize}
        et constatez quelles erreurs sont générées. 
    \end{Exercice}

**Comment by fservais-heb** [comment]
Parfait je n'avais pas vu le nouvel exercice. Merci.
