### ISSUE TITLE
pseudocode

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#48]
quelques remarques faites par mail qui prennent un peu plus de temps à corriger et demande l'avis « des autres ». 

1. pour l'entête d'un algo, je garderais la syntaxe java qui n'est pas plus 
lourde, si on omet les static, public & autres:

         algorithm algoName(param: type1) -> type2

    peut s'écrire:

         type2 algoName(param: type1)

**Comment by YoungFrog** [comment]
Ceci n'est pas important, je propose de laisser ça à l'année prochaine (voire wontfix)
