### ISSUE TITLE
Harmonisation des styles

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#5]
(ceci sera à faire vers la fin, quand le contenu sera plus ou moins fixé...)

Utiliser des environnements pour 
/Exemple/, /Rappel/ et peut être d'autres.

**Comment by pbettens** [comment]
tu parles du cours ou des tds ?

**Comment by YoungFrog** [comment]
Des TDs

**Comment by mcodutti** [comment]
Fait !
