### ISSUE TITLE
envl/td1 - drive d'équipe

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#52]
Dans la partie sur le drive Google, ce serait bien de mentionner l'existence des drives d'équipes parce qu'ils ne connaissent pas ce concept et de mentionner : 
- le drive d'équipe du Conseil étudiant
- celui pour les étudiants

**Comment by pbettens** [comment]
… tiens je pourrais ajouter ça aussi à mon document d'accueil…
