### ISSUE TITLE
envl/td1 - profil des navigateurs et gestion d'un double compte Google

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#53]
Quand nous publions un document sur le drive, nous avons souvent des demandes d'accès refusé d'un étudiant parce qu'il tente d'y accéder avec son compte privé et pas son compte @he2b.
Les navigateurs (en tout cas chrome et firefox) permettent de gérer des profils différents ce qui permet d'avoir 2 fenêtres bien différenciées : une où ils sont reconnus avec leur compte privé et une avec leur compte @he2b.

Vu qu'on parle des outils dans ce td1, c'est un bon endroit pour aborder ce point et les aider.
Je sais que je ne fait ici aucune proposition concrète et qu'il reste peu de temps.

**Comment by pbischop** [comment]
@MCD : J'ai rajouté ta remarque dans la section sur le drive.
