### ISSUE TITLE
envl/td2 - installation de linux à la maison

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#55]
> Je n’ai pas Linux à la maison. Je peux quand même terminer mon TD ?
Non. Vous devrez rapidement disposer d’un Linux fonctionnel à la maison. Ce qui devrait d’ailleurs être le cas si vous avez fait les exercices demandés au cours d’introduction à
l’OS.

Intro OS n'est plus donné en début d'année et ne peut donc plus voir comment installer un linux à la maison. Je suis d'ailleurs perdu; ce sera fait quand en DEV1 ?

**Comment by YoungFrog** [comment]
Comment était-ce fait en INT-SYS ? Peut-on récupérer la méthode ? J'avais posé la question à quelqu'un mais je n'ai pas bien retenu la réponse.

Pour moi le plus simple est d'avoir une clef USB avec un linux qui juste marche. On pourrait faire un TDxx-prépa de ce genre ; j'imagine qu'il y a une image Ubuntu qui jouera parfaitement ce rôle. Cela conviendrait-il ou faut-il qqch de plus élaboré ?

**Comment by mcodutti** [comment]
En INT1, l'idée était de proposer qqchose de fonctionnel rapidement sans risque de casser leur Windows et d'ensuite leur donner les outils de compréhension pour aller plus loin.

séance 1) Qu'est ce qu'un OS, une machine virtuelle, installer Virtualbox avec une image linux pré-installée et configurée pour les TDs (à la semaine 2, ils pouvaient terminer leur tds DEV1 à la maison)
séance 2) les manipulations d'administration de base : gestion des utilisateurs, des logiciels... 
Installer un OS dans une machine virtuelle à partir des iso d'installation
séance 3) Se repérer dans la hiérarchie standard (etc, bin, var, lib, proc, dev, boot...). La notion de systèmes de fichiers et les systèmes de fichiers les plus courants (fat, ext, ntfs...). La notion de partition, comment les visualiser, les modifier... 
séance 4) Les étapes d'allumage d'un ordinateur : post, bios/uefi, mbr/gpt, grub...
séance 5) Installer un OS en single boot/dual boot : les questions à se poser avant, les décisions à prendre, les parties délicates, comprendre les questions qui seront posées...

Ce serait dommage que tout ceci disparaisse, ça leur est utile (et puis on s'est engagé, au moins pour une partie).

**Comment by mcodutti** [comment]
Les slides sont toujours disponibles sur poÉSI et ici : git@github.com:HEB-ESI/INT1-SYS-Slides-Intro-OS.git

**Comment by YoungFrog** [comment]
Comme je l'ai compris, on s'est engagé à intégrer l'équivalent de la "séance 1" de INT1-SYS, dans DEV1. (Les autres séances restent-elles, sous une forme ou l'autre, en INT1 ?)

Le faire en ENVL semblerait logique, mais ce serait perdre du temps de labo à des choses pour lesquelles un labo ne sert à rien (on n'a pas de virtualbox à lancer sur les machines des labos, on ne sait pas leur montrer grand chose à part wikipedia !).

Le faire en JAVL est un contresens, donc il reste JAV.

Somme-nous prêts à prendre 1h ou 2h de JAV pour ceci ? Je peux le concevoir sous forme d'intermède vers la séance 5 (semaine 3), mais n'est-ce pas trop tard ?

**Comment by pbettens** [comment]
le mieux, c'est sans doute de montrer ça au cours… mais quand, combien de temps et comment ?

ceci dit, je suis pour leur donner des pistes, les laisser faire chez eux et répondre ensuite à leur question. c'est inutile de faire une installation devant eux.

**Comment by YoungFrog** [comment]
Quand je disais "le faire" je ne pensais pas à l'installation, mais à expliquer le contenu de la séance 1 du dépôt dont Marco a indiqué l'adresse.

**Comment by pbettens** [comment]
je mettrais ça en séance 3 ou 4 (aka en semaine 2). 
il faudrait récupérer le document int… dont parle marco et en faire un document utilisable au cours lors de cette semaine là.

ça devrait prendre 20-30min cette présentation ?

**Comment by YoungFrog** [comment]
Une proposition a été envoyée par email
