### ISSUE TITLE
envl/td5 - typo

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#61]
- s/à réaliser/a réalisé/

**Comment by YoungFrog** [comment]
Je ne vois pas de quoi il s'agit. C'est bien le TD git ? J'ai deux occurrences de "à réaliser":

> 2 matches for "à réaliser" in buffer: git.org
>      41:Au travers de ce TD nous vous montrerons comment Git aide à réaliser ces
>     104:   actions à réaliser. Elles sont indiquées par le marquage "Action" sur fond rouge (voir ci-dessus). Ces actions
> 

aucune ne me semble se prêter à la modif proposée.

**Comment by mcodutti** [comment]
J'avais lu autre chose... !?

**Comment by YoungFrog** [comment]
Deux options:
- j'avais déjà rectifié plusieurs choses suites aux remarques de Pierre, peut ceci en faisait partie
- tu deviens vieux, la vue baisse et la mémoire flanche ;)
