### ISSUE TITLE
envl/td5 - longueur du TD

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#65]
Il est important que la grande majorité des étudiants arrivent au bout du TD pendant les 2h de labo (enfin, la partie obligatoire : jusque remote). Ici, c'est jouable si : 
- On insiste bien pour qu'ils ne fassent **pas** les parties en vert pendant le labo
- On enlève la partie sur diff. Personnellement, je la mettrais dans la partie "pour aller plus loin..." et j'y ajouterais un texte pour expliquer qu'on peut le faire aussi de façon plus conviviale sur gitlab.

**Comment by YoungFrog** [comment]
Lorsque j'ai créé la partie "Pour aller plus loin" (mardi passé), la partie "diff" s'y est retrouvée directement. Si tu as une partie "pour aller plus loin" et la partie "diff" est avant, je ne comprends pas comment.

**Comment by mcodutti** [comment]
p12 ?

**Comment by YoungFrog** [comment]
Ah oui, le `git show`. Mais je trouverais dommage de le virer celui-là. C'est le seul endroit où on "visualise" l'effet d'un commit. Tu trouves que ça prend du temps ? tu virerais peut-être même toute la section "Affichage de l’historique et des commits" ?

**Comment by YoungFrog** [comment]
@mcodutti Ok j'ai bougé la partie /git show/ vers une section hors programme. Dans la mesure où je ne donne pas le TD, ton avis a plus de force que le mien ;-)
