### ISSUE TITLE
envl/td5 - git et Netbeans

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#66]
Le document se contente d'écrire

> Comme vous l’avez noté dans le menu Team, Netbeans offre une certaine dose d’intégration
avec Git. À vous de découvrir ce que vous pouvez faire depuis Netbeans.

Je trouve dommage d'être si succinct alors que Jonathan avait écrit tout un TD introduisant git sur Netbeans. N'y a-t-il rien à récupérer ?

**Comment by pbettens** [comment]
ce serait bien de l'ajouter si jonathan est d'accord… ce qui allongera encore le td. 

je me dis que le td pourrait être scindé:

- la partie «rouge et un peu plus » deviendrait le td. bcp plus cours donc. 
- le reste deviendrait un document de référence proposé en dev1… et que les étudiant·es pourraient réutiliser ensuite à leur meilleur convenance. 

qu'en pensez-vous ?

@YoungFrog tu penses que tu aurais le temps de faire ça ?

**Comment by YoungFrog** [comment]
Je dois dire que je n'avais pas la motivation pour regarder à git-sur-netbeans quand j'ai écrit mon truc. Je devrais lire le TD, peut-être en discuter avec quelqu'un qui l'a déjà donné pour voir comment l'intégrer de façon adéquate. Une simple concaténation aurait-elle du sens ? i.e. voir les concepts depuis la ligne de commande puis les même depuis netbeans.

**Comment by YoungFrog** [comment]
@mcodutti J'ai intégré quelques éléments du TD de Jonathan dans une annexe. (Les mettre dans la partie obligatoire m'eut semblé incohérent avec #65.)
