### ISSUE TITLE
envl/td5 - commit et option -a

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#67]
@YoungFrog ,
Tu n'introduis nulle part l'option `-a` de commit (j'avoue, je l'utilise tout le temps !).
Est-ce un choix délibéré ? Une bonne pratique ?
Pense-tu qu'il doit en être de même quand on l'utilise via l'interface Netbeans ?

**Comment by YoungFrog** [comment]
Je n'utilise jamais `-a` parce que
- je fais parfois des modifications sans lien les une aux autres, et je veux sélectionner ce qui va dans le commit
- ça me force à relire un minimum mes changements
- s'il y a de nouveaux fichiers, ils restent sur le carreau
- la vraie raison : je n'utilise quasiment plus git en ligne de commande, j'utilise généralement un outil intégré à Emacs ;)
