### ISSUE TITLE
référence lda - typo

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#69]
s/ambigü/ambigu/

**Comment by pbettens** [comment]
je ne trouve pas « ambigü » dans le document.
«ambigüe» et «ambigüité» oui et l'orthographe est bonne.

peux-tu préciser la page ?

**Comment by pbettens** [comment]
… ok, ce n'est pas dans le cours mais dans la référence (comme tu l'indiques bien)… je vais voir.
