### ISSUE TITLE
fiche 12 (tri)

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#7]
ajouter les codes java pour le tri bulle et le tri par minimas successifs.

**Comment by YoungFrog** [comment]
Cela me semble moins important, on pourra le présenter aux cours si nécessaire, et le temps joue contre nous. Je propose donc de laisser pour l'an prochain.

**Comment by pbettens** [comment]
done

**Comment by pbettens** [comment]
oups, fait dans le cours mais pas encore dans la fiche…
