### ISSUE TITLE
référence LDA - switch

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#70]
Un mot pour le cas où il y a plusieurs valeurs pour le même cas ?
Pas de break obligatoire ->

> case 1:
case 2: faire qqchose 

est ambigu (cas 1 = ne rien faire ou faire qqchose ?) 

Une remarque pour dire que le switch accepte une expression et pas juste un nom de variable ?

**Comment by YoungFrog** [comment]
Une possibilité serait d'exiger un commentaire s'ils veulent des break implicites.
Quant aux différents cas de même valeur, on peut permettre des "ou" p.ex:
```
switch foo: // avec des break implicites
case 0:
case 1 or 2 or ... or 9: faire qqch
default: erreur
```
Sans le commentaire, on suppose que ça enchaîne comme en Java
```
case 1 or 2 or ... or 9: faire qqch // et on enchaîne :
case 0: faire le minimum; break
default: erreur
```
