### ISSUE TITLE
référence LDA - type de passage de paramètres

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#72]
Je comprend l'idée de supprimer le passage OUT mas quand est-il d'une situation comme celle-ci ?

On veut un algo qui cherche une valeur dans un tableau et indique si elle si trouve et, si oui, où ?
- Java est obligé de retourner uniquement une position avec une valeur impossible si pas trouvé
- d'autres langages comme C/C++ s'en sortent en proposant le booléen en retour et la position en paramètre OUT (passage par référence si je me rappelle bien du terme)

Dans les quelques situations (rares) où ça apparaissait dans le cours, on modifie la demande ?
@YoungFrog : pas besoin pour le cours d'algo III ? Vous introduirez à ce moment là les nuances ?

Da façon générale si on veut réduire/simplifier les passages de paramètres à ce qui existe en Java, j'imagine qu'on ne va pas permettre de dire qu'un entier est en IN/OUT ni qu'un tableau est en IN. On pourrait alors aller un pas plus loin et dire que le type de passage est induit par le type de la variable (toujours IN sauf tableau/structure/objet)

D'un autre coté, je noterais aussi qu'on perd en expressivité. Dire q'un tableau est en IN pur apporte de l'information sur ce que fait l'algorithme en question et sur l'assurance qu'il ne va pas le modifier.

**Comment by YoungFrog** [comment]
Pour ton exemple d'un algo de recherche qui doit renvoyer un bool et un int, mon avis est qu'on peut introduire plusieurs valeurs de retour : je trouve ça plus naturel que d'avoir un paramètre out. Mais ce n'est pas ce qui a été choisi, et je suis ok avec ça.

Pierre avait déjà signalé par ailleurs qu'il préférait garder IN/OUT notamment pour garder l'ouverture vers le C++. Autant que je puisse en juger, quelqu'un (j'imagine Pierre) a déjà transformé les Out en In/Out, donc on peut fermer l'issue si j'ai bien compris. Sinon on peut rouvrir.

En ALG III on y fait sans doute parfois référence mais l'aspect IN, OUT, IN/OUT n'est jamais central au cours, en tout cas pas comme je l'ai donné. Je devrai repasser au travers du syllabus l'année prochaine pour vérifier.

Sur le fond : c'est vrai qu'on perd en expressivité, mais je crois qu'on peut expliquer ces IN, OUT, IN/OUT plus tard, lorsque les étudiants peuvent comprendre les diverses implications d'un tel marquage, par exemple après avoir vu des langages où cela a du sens. Je suis cependant tout à fait favorable à leur apprendre "final" en DEV1 par exemple, dont la sémantique est bien définie (et proche de IN pour les types primitifs).
