### ISSUE TITLE
envl / td01 : Linux vs GNU / Linux

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#76]
désolé pour ce 1er issue un peu trollesque. et donc, sans vouloir lancer un troll, je me rappelle de rms qui demande de parler de GNU / Linux plutôt que simplement Linux. je vois que dans le td01, on parle simplement de Linux. personnellement, je préfère GNU / Linux (en tout cas quand on l'écrit). cependant, si c'est un choix de la majorité, no problemo pour moi et on ferme cet issue asap :-)

**Comment by YoungFrog** [comment]
Je préfère aussi GNU / Linux, j'ai plus l'habitude, même si en pratique on en oublie sans doute encore une bonne partie en ne citant que ces deux-là...
