### ISSUE TITLE
envl / tous les td : \emph{} pour l'emphase

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#79]
miette suivante : dans la section 2.1 Imprimer, l'emphase est indiquée en utilisant l'italique (installer), tandis que dans les consignes, elle est rendue avec du texte gras (coopérer). pour ce que j'en sais et pour ce que LaTeX fait avec \emph{}, c'est l'italique qui prévaut en français. pourquoi ne pas simplement utiliser \emph{} et laisser LaTeX gérer selon babel ?

**Comment by YoungFrog** [comment]
Au bout de presque un an je pense que personne ne le fera plus.

**Comment by pbettens** [comment]
ah ah, nfs t'a fait mentir ;-)
