### ISSUE TITLE
labo java - td1

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#8]
- le screenshot « package » ne correspond pas au texte. dans le texte c'est g12345 et sur le screenshot, c'est esi. 

- p4 « lancer le programme…» j'ajouterais une phrase du style: « vous devriez voir apparaitre le mot « hello » en bas de l'écran. 

- p5 s/programme principale/programme principal/

- p5 même remarque. je ferais suivre «cliquer sur run file» d'une phrase du style. vous devriez voir apparaitre Hello Jean-Kévin.

- p7 et 8 après avoir montrer le code de l'aire du rectangle, j'ajouterais une phrase demandant de tester ce code. 
     je vois que tu ne le demandes pas avant non plus. tu peux laisser tomber ou écrire plut tôt dans le td que c'est une bonne idée de tester les codes proposés. 

- exercice 9. il faut peut-être préciser qu'il ne faut pas vérifier que l'entrée est correcte. on peut même leur dire qu'ils peuvent essayer avec d'autres valeurs… laisse tomber, on dira ça oralement. 

- s/clique/clic/ (je ne sais plus où)

**Comment by fservais-heb** [comment]
closed by d11973c7d5942d3419b43ec02e6e024f4144c142
