### ISSUE TITLE
envl / td01 : points à lire avant les labos...

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#80]
dans la section 1.2 Ressources, je ne comprends pas la dernière phrase décrivant le guide visuel Linux : 

 Certains points sont à lire avant de venir au laboratoire

de quels points et de quel laboratoire s'agit-il ? pour le labo, je suppose que c'est envl, mais pour les points, c'est obscur : une liste des points est-elle fournie? rem. comme je ne suis pas inscrit à la formation, je n'ai pas accès aux documents de la rubrique Aide etc.

**Comment by mcodutti** [comment]
Obsolète. Plus de document à lire avant.
