### ISSUE TITLE
envl / td01 : étymologie des commandes unix

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#82]
ne serait-il pas bien d'expliquer le plus rapidement possible l'origine des noms des commandes linux ?

dans la section 3.4 : 
La commande pour changer le mot de passe est passwd.
deviendrait : 
La commande pour changer le mot de passe est passwd. Son nom vient du mot \textit{password}.
(ici c'est trivial)

de même dans la section 3.5, juste avant Tutoriel 3 : 
 Simplement avec la commande ls que vous avez déjà rencontrée.
deviendrait : 
 Simplement avec la commande ls que vous avez déjà rencontrée et dont le nom est issu du mot \textit{list}.

dans Tutoriel 3 : 
 Cette commande demande de se déplacer dans le dossier bin.
deviendrait : 
 Cette commande (abréviation de \textit{change directory}) demande de se déplacer dans le dossier bin.
et on pourrait virer sa signification au 1er item du paragraphe Dossier courant.

le paragraphe quelques commandes en plus... deviendrait : 
Il est temps de voir quelques commandes supplémentaires.
. cat nomDuFichier affiche à l’écran le contenu du fichier dont le nom est donné. Ce
n’est pas un éditeur, on voit le contenu et c’est tout. Son nom vient du mot \textit{concatenate}.
. mkdir nomDuDossier crée un dossier (vide) nommé "nomDuDossier". Son nom vient de l'expression \textit{make directory}.
. mv nomDuFichier nouveauNomDeFichier renomme le fichier donné "nomDuFichier"
sous le nom "nouveauNomDeFichier". Son nom a pour origine le mot \textit{move}.
. mv nomDuFichier nomDuDossier déplace le fichier donné dans le dossier indiqué.
. cp nomDuFichier nouveauNomDeFichier crée une copie du fichier sous le nom
"nouveauNomDeFichier". Son nom est issu du mot \textit{copy}.
. cp nomDuFichier nomDuDossier copie le fichier donné dans le dossier indiqué.
. rm nomDuFichier détruit le fichier dont on donne le nom. Son nom vient de \textit{remove}.
. rmdir nomDuDossier détruit le dossier dont on donne le nom. Attention, le dossier
doit être vide ! Son nom a pour origine l'expression \textit{remove directory}.

**Comment by YoungFrog** [comment]
Au bout de presque un an je pense que personne ne le fera plus.

**Comment by nvansteenkiste** [comment]
@mcodutti l'a fait :D
