### ISSUE TITLE
envl / td01 : section Éditeur : article et espace

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#85]
détails (suite)

je titrerais la section 3.6 « Éditeur de texte » plutôt que « L'éditeur » : 

+ le « de texte » par soucis de précision ;
+ l'absence de « L' » par préférence : à ce propos comme pour « Consignes » et « Ressources » qui ne sont pas précédés d'article, je les virerais tous dans les titres : « Mode console », « Dossier personnel et dossier courant », etc.

dans la section 3.6, il y a 2 endroits où j'ai l'impression qu'il manque une espace. je les indique ici par une étoile : 
+ le ^*représente la touche Ctrl
+  la commande ls.*Vous pouvez constater

**Comment by nvansteenkiste** [comment]
j'ai ouvert une [issue](https://github.com/HEB-ESI/dev1/issues/97) pour tous les td relative à l'utilisation de l'article dans la titraille.

**Comment by YoungFrog** [comment]
Au bout de presque un an je pense que personne ne le fera plus. J'ai regardé rapidement les soucis d'espaces manquante et je n'ai pas vu ce dont il s'agissait.
