### ISSUE TITLE
aide-mémoire / Se connecter à Windows

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#86]
> Votre mot de passe initial vous a été communiqué par le professeur lors du premier 
laboratoire

Ce n'est plus vrai depuis quelques années déjà ;)
Remplacer par 
> Votre mot de passe est repris sur le document qui vous a été remis lors de votre inscription

**Comment by pbettens** [comment]
… j'écrirais

> Votre mot de passe initial vous a été communiqué.

(je pense qu'ils le reçoivent par mail)
