### ISSUE TITLE
envl/aide : plus de groupe `etudiants1`

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/dev1#87]
L'aide-mémoire et le guide visuel font référence à un groupe `etudiants1` sur linux1 mais il n'existe plus.
Un étudiant appartient aux groupes `userss` et `etudiants` uniquement. 
La référence est faite :
- dans l'aide-mémoire au point 21 
- dans le guide visuel aux points  15 et 16

**Comment by nvansteenkiste** [comment]
j'ai constaté hier (01/10/2018) que le groupe `etudiants1` existe.
