### ISSUE TITLE
envl / aide-mémoire : se connecter à windows

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#88]
au 2e point : « Votre mot de passe initial vous a été communiqué par le professeur lors du premier
laboratoire. » ce n'est plus vrai.

les 3e et 4e points sont alignés différemment des autres sans que j'en comprenne la raison.

au 4e point : « local 501 » est plus précis etc. que « local du 5 ème ».

**Comment by YoungFrog** [comment]
L'alignement différent c'est parce que ce sont des "sous-points". Les ponts principaux sont username, password, domain ; les points en retraits font partie du point "password".

**Comment by YoungFrog** [comment]
La première remarque c'était la même chose que #86 qui avait déjà été arrangé entre-temps
La dernière a été prise en compte dans https://github.com/HEB-ESI/dev1/commit/452795039f8afcc1950c6f64bf921c6df1918b04  (dans le message qui dit "YoungFrog closed" le nom du commit est donné).
J'ai également modifié le type de "bullet" pour essayer de clarifier que ce sont des "sous-points". Si ce n'est pas plus clair tu peux ré-ouvrir bien sûr.
