### ISSUE TITLE
 envl / aide-mémoire : changer son mot de passe sous Windows

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#89]
au 1er point : on dit généralement « Ctrl - Alt - Delete » plutôt que « Alt - Ctrl - Delete ».

au 2e point : j'ai le bouton « Change a password... » plutôt que « Change Password »

**Comment by YoungFrog** [comment]
J'ai modifié, et j'ai aussi ajouté une phrase pour expliquer comme appuyer sur Ctrl Alt Del.
