### ISSUE TITLE
labo java - td2

### ISSUE THREAD

**Issue by pbettens** [HEB-ESI/dev1#9]
je préfère que l'on parle de **nombres décimaux** plutôt que de « nombres à virgule ».

… et je viens de voir ton mail me demandant d'arrêter de lire. pouf.

**Comment by fservais-heb** [comment]
on a eu cette discussion.
J'avais mis réels, on a discuté, j'ai changé pour 'nombres à virgule', Delannoy utilise 'flottants', d'autres 'rationnels', d'aucun proposait 'double'.
Si tu veux changer n'hésite pas, je ne suis pas contraire ! :-)

Je ferme l'issue.
