### ISSUE TITLE
 envl / aide-mémoire : s'absenter un instant

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#90]
+ « Ctrl - Alt - Delete » est davantage dans les usages que « ALT-CTRL-DEL».
+ « Windows - L » est beaucoup plus simple pour verrouiller la machine : c'est alors fait en une seule étape, contrairement à la méthode préconisée où il est facile d'oublier la seconde étape avec pour conséquence que la machine n'est pas verrouillée.
+ verrouiller une machine n'empêche pas  un autre utilisateur d'y accéder : la phrase finale est-elle ok ?

**Comment by YoungFrog** [comment]
- J'ai modifié le ctrl alt del
- pour Win-L : ok j'ai modifié aussi
- j'ai enlevé la phrase finale qui n'est effectivement pas pertinente (en plus d'être vexatoire à mon avis)
