### ISSUE TITLE
ENVL/Git Clone git.esi-bru from linux1 fails with HTTPS

### ISSUE THREAD

**Issue by YoungFrog** [HEB-ESI/dev1#91]
Il semble qu'il y a une erreur au moment de cloner git.esi-bru en HTTPS depuis linux1.

Je n'ai pas vraiment cherché, mais je confirme le souci quand je teste de cloner en https. Par contre en ssh ça marche.

Je peux proposer de modifier le TD git pour cloner en ssh tout simplement, mais SRV semblait avoir d'autres idées.

```
nri@srv-pdg13:~/projet-git> GIT_TRACE=1 git clone https://git.esi-bru.be/pbt/accueil
trace: built-in: git 'clone' 'https://git.esi-bru.be/pbt/accueil'
Cloning into accueil...
trace: run_command: 'git-remote-https' 'origin' 'https://git.esi-bru.be/pbt/accueil'
error: Unknown SSL protocol error in connection to git.esi-bru.be:443  while accessing https://git.esi-bru.be/pbt/accueil/info/refs

fatal: HTTP request failed

nri@srv-pdg13:~/projet-git> openssl s_client -connect git.esi-bru.be:443 -prexit
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 209 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 209 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---

nri@srv-pdg13:~/projet-git> GIT_TRACE=1 git clone git@git.esi-bru.be:pbt/accueil
trace: built-in: git 'clone' 'git@git.esi-bru.be:pbt/accueil'
Cloning into accueil...
trace: run_command: 'ssh' 'git@git.esi-bru.be' 'git-upload-pack '\''pbt/accueil'\'''
git@git.esi-bru.be's password:
```

 cc @fservais-heb et @pbettens (sur le conseil de srv)

**Comment by fservais-heb** [comment]
- J'ai esasyé sans succès en désactivant ssl : git config --global http.sslVerify false
- FMA m'a dit qu'il n'est pa possible de mettre à jour la linux1 ou en tout cas certaines parties de linux1.
Et qu'il allait essayer certaines bidouilles. Et donc apparement sans succès.

**Comment by YoungFrog** [comment]
Heck, j'aurais dû écouter mes collègues qui me disent que non ça marche pas en ssh. Parce que non, ça marche pas en ssh.

**Comment by YoungFrog** [comment]
Les commandes que je donnais ne fonctionnent pas mieux. J'ai aussi testé GIT_CURL_VERBOSE mais ça ne donne pas vraiment d'info supplémentaire intéressante. Tout ce que je peux dire c'est que git.esi-bru.be ferme la connection abruptement après les premiers bytes transmis.

Cela dit j'ai commité un workaround : faire le clone en ssh, comme discuté par email. Je referme donc l'issue.

**Comment by pbettens** [comment]
... et le problème est le même avec github... c'est donc bien linux1 qui fail ;-)
