### ISSUE TITLE
envl / aide-mémoire : Les casiers électroniques sous Windows

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#94]
+ « \\SRV-PDG17\eCasier\ACRO  » plutôt que « \\Srv-pdg04\eCasier\ACRO »

+ la phrase : « Si vous déposez tout un dossier, le PC affichera quelques avertissements mais les
fichiers seront bien copiés. » ne me semble pas tout à fait correcte. j'ai de temps en temps observé des pertes partielles mais plus souvent totales des contenus de dossiers déposés. c'est pourquoi je demande désormais systématiquement d'archiver dans 1 fichier et de déposer ce fichier. là, si ça ne passe pas (ce qui arrive) on le remarque tout de suite :-)

**Comment by YoungFrog** [comment]
J'ai modifié le texte, mais je n'ai pas pour autant mis à jour pour 2019-2020 (et je ne pense pas le faire car je trouve le document globalement très peu utile).
