### ISSUE TITLE
envl / tous les td : titraille : article

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#97]
un premier point où il me semble manquer de cohérence est le suivant. 

lorsque le titre d'un chapitre, d'une section etc. est un nom, il est parfois garni d'un article, parfois pas. il faut harmoniser. j'enlèverais systématiquement l'article pour ne garder que le nom nu : p. ex. « Permissions » à la place de « Les permissions » dans le td02.

**Comment by YoungFrog** [comment]
Au bout de presque un an je pense que personne ne le fera plus.
