### ISSUE TITLE
envl / tous les td : titraille : nom vs. verbe

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#98]
un deuxième point relatif à la titraille où il me semble manquer de cohérence est le suivant.

on a tantôt des noms, tantôt des verbes à l'infinitif en titre. j'essaierais d'uniformiser en ne choisissant que des noms. par exemple « Connexion » à la place de « Se connecter » dans le td01.

ça donne parfois moche avec un nom. je ne suis pas certain qu'il faille être rigoureusement strict ici.

**Comment by YoungFrog** [comment]
Au bout de presque un an je pense que personne ne le fera plus.
