### ISSUE TITLE
envl / tous les td : nom de commande et style

### ISSUE THREAD

**Issue by nvansteenkiste** [HEB-ESI/dev1#99]
au long des td, on trouve des commandes linux écrites avec de multiples styles : cd, \texttt{cd}, \textbf{cd}, etc. il faut certainement unifier les écritures. passer par la définition d'une commande LaTeX nous permettrait de changer d'avis et de style. elle existe d'ailleurs peut-être déjà dans les styles LaTeX de l'esi :-D

**Comment by mcodutti** [comment]
Je viens d'ajouter dans le style ESI (en m'inspirant des noms dans html5)

- `\kbd` : pour un entrée clavier, une commande à taper telle quelle
- `\samp` : pour le résultat d'une commande, un output de programme
- `\abbr` : pour une abréviation, un sigle, acronyme
- `\name` : pour un nom de logiciel

Pour le moment, `\kbd` et `\samp` sont des `\texttt` et `\abbr` et `\name` des `\bsc`.
Le tout est dans common.sty et automatiquement chargé dans tous les types de documents ESI (cf. doc mise à jour)
